### PR TITLE
Adding link to my package repo

### PR DESCRIPTION
**Pull request by Beta-Cygni-A**
Adding link to my package repo

### CODE REVIEW

**Comment by rozniak** [comment]
@Beta-Cygni-A Sorry I never replied - I'll do GitHub releases at some point when setup is done, so it should be at a point where it's more like a 'somewhat worth using' phase. :grin:

**Comment by Beta-Cygni-A** [comment]
No worries. We talked about it in an email. Today I saw there was a pull request and then I looked at it and I was like oh yeah I still have that up lol. Yeah that will be cool. One question though, do the names of the packages created change often? I was thinking, the scripts I wrote, all they did was install the different specific packages for a OS using the OS specific package manager and I listed them in order of what needed installed first. I get not hosting packages just yet until a release system is built, but what do you think of having those scripts over here?  Or is that something to leave of for now given there is a python installer and a port of it in progress?

**Comment by rozniak** [comment]
I don't really want to change the package names because it does cause a bit of agg to deal with. Unfortunately a couple like `wintc-shell-run` and `wintc-shell-winver` are inconsistent with like `wintc-taskband` and `wintc-desktop` (which are obv both part of the shell), but it might just be something to lump with.

I would rather keep working on a dedicated setup process than an interim script thingy. I think it's better to have it all done up in a proper release than having a kind of 'heres a release but not really' tool in the repo. :thinking:

**Comment by Beta-Cygni-A** [comment]
Oh ok, that makes sense.

**Pull request closed without merging**
