### PR TITLE
Added a comprehensive guide on setting up xfce-winxp-tc for beginners

### PR DESCRIPTION
**Pull request by acdavit**

### CODE REVIEW

**Comment by rozniak** [comment]
Sorry I haven't said anything on this. I will probably try to massage this work into the Wiki once I have some time to do so. Apologies I haven't gotten around to it sooner.

**Comment by acdavit** [comment]
@rozniak 

Thanks for replying.

If there are any mistakes or inaccuracies in my contribution, feel free to let me know and I'll fix them ASAP. 

I'm free this summer and I'd love to contribute as much as I can with my free time to this project.

**Comment by rozniak** [comment]
Hello again!

I have just put up a condensed version of this on the Wiki here: https://github.com/rozniak/xfce-winxp-tc/wiki/Manual-configuration-following-install

Think it covers everything? I had a look over what I normally do alongside what you have written here, and tried to keep it down to a brief format to avoid it overwhelming people. :cold_face:

**Comment by acdavit** [comment]
Looks great. Comprehensive, and simple.

**Comment by rozniak** [comment]
@acdavit I want to say thanks again for your contribution to writing a better guide, it's much appreciated! :grin:

**Comment by acdavit** [comment]
You're welcome.

**Pull request closed without merging**
